version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 6022:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pg:
